//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class C18NO7_ExcelE_subset
    {
        public string UniProt_ID { get; set; }
        public string SNV_Key { get; set; }
        public string PDB_File_No { get; set; }
        public string Drug_PDB_ID { get; set; }
        public string Human_Gene_Location { get; set; }
        public string Nucleotide_1_Position { get; set; }
        public string Nucleotide_2_Position { get; set; }
        public string Nucleotide_3_Position { get; set; }
        public string P1W { get; set; }
        public string P2W { get; set; }
        public string P3W { get; set; }
        public string P1M1 { get; set; }
        public string P1M2 { get; set; }
        public string P1M3 { get; set; }
        public string P2M1 { get; set; }
        public string P2M2 { get; set; }
        public string P2M3 { get; set; }
        public string P3M1 { get; set; }
        public string P3M2 { get; set; }
        public string P3M3 { get; set; }
        public string P1W_Nucleotide { get; set; }
        public string P2W_Nucleotide { get; set; }
        public string P3W_Nucleotide { get; set; }
        public string P1M1_Nucleotide { get; set; }
        public string P1M2_Nucleotide { get; set; }
        public string P1M3_Nucleotide { get; set; }
        public string P2M1_Nucleotide { get; set; }
        public string P2M2_Nucleotide { get; set; }
        public string P2M3_Nucleotide { get; set; }
        public string P3M1_Nucleotide { get; set; }
        public string P3M2_Nucleotide { get; set; }
        public string P3M3_Nucleotide { get; set; }
        public string P1W_Nucleotide_Triplet { get; set; }
        public string P2W_Nucleotide_Triplet { get; set; }
        public string P3W_Nucleotide_Triplet { get; set; }
        public string P1M1_Nucleotide_Triplet { get; set; }
        public string P1M2_Nucleotide_Triplet { get; set; }
        public string P1M3_Nucleotide_Triplet { get; set; }
        public string P2M1_Nucleotide_Triplet { get; set; }
        public string P2M2_Nucleotide_Triplet { get; set; }
        public string P2M3_Nucleotide_Triplet { get; set; }
        public string P3M1_Nucleotide_Triplet { get; set; }
        public string P3M2_Nucleotide_Triplet { get; set; }
        public string P3M3_Nucleotide_Triplet { get; set; }
        public string P1W_Amino_Acid_ { get; set; }
        public string P2W_Amino_Acid_ { get; set; }
        public string P3W_Amino_Acid_ { get; set; }
        public string P1M1_Amino_Acid_ { get; set; }
        public string P1M2_Amino_Acid_ { get; set; }
        public string P1M3_Amino_Acid_ { get; set; }
        public string P2M1_Amino_Acid_ { get; set; }
        public string P2M2_Amino_Acid_ { get; set; }
        public string P2M3_Amino_Acid_ { get; set; }
        public string P3M1_Amino_Acid_ { get; set; }
        public string P3M2_Amino_Acid_ { get; set; }
        public string P3M3_Amino_Acid_ { get; set; }
        public string SNV_P1W_ID { get; set; }
        public string SNV_P2W_ID { get; set; }
        public string SNV_P3W_ID { get; set; }
        public string SNV_P1M1_ID { get; set; }
        public string SNV_P1M2_ID { get; set; }
        public string SNV_P1M3_ID { get; set; }
        public string SNV_P2M1_ID { get; set; }
        public string SNV_P2M2_ID { get; set; }
        public string SNV_P2M3_ID { get; set; }
        public string SNV_P3M1_ID { get; set; }
        public string SNV_P3M2_ID { get; set; }
        public string SNV_P3M3_ID { get; set; }
        public string Drug_Inter__Pred__P1W { get; set; }
        public string Drug_Inter__Pred__P2W { get; set; }
        public string Drug_Inter__Pred__P3W { get; set; }
        public string Drug_Inter__Pred__P1M1 { get; set; }
        public string Drug_Inter__Pred__P1M2 { get; set; }
        public string Drug_Inter__Pred__P1M3 { get; set; }
        public string Drug_Inter__Pred__P2M1 { get; set; }
        public string Drug_Inter__Pred__P2M2 { get; set; }
        public string Drug_Inter__Pred__P2M3 { get; set; }
        public string Drug_Inter__Pred__P3M1 { get; set; }
        public string Drug_Inter__Pred__P3M2 { get; set; }
        public string Drug_Inter__Pred__P3M3 { get; set; }
        public string NCBI_Gene_Name { get; set; }
        public string NCBI_geneID { get; set; }
        public string chain { get; set; }
        public string SNV_Key_orig { get; set; }
    }
}
