//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrugProNETEntities : DbContext
    {
        public DrugProNETEntities()
            : base("name=DrugProNETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drug_Information> Drug_Information { get; set; }
        public virtual DbSet<PDB_Distances> PDB_Distances { get; set; }
        public virtual DbSet<PDB_Information> PDB_Information { get; set; }
        public virtual DbSet<Protein_Information> Protein_Information { get; set; }
        public virtual DbSet<C18NO7_ExcelE_subset> C18NO7_ExcelE_subset { get; set; }
        public virtual DbSet<PDB_Interactions> PDB_Interactions { get; set; }
    }
}
