//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_Information
    {
        public string Drug_PDB_ID { get; set; }
        public string PDB_File_ID { get; set; }
        public string Drug_Name_for_Pull_Down_Menu { get; set; }
        public string Drug_Common_Name { get; set; }
        public string Drug_Chemical_Name { get; set; }
        public string Other_Drug_Name_Alias { get; set; }
        public string Drug_InChl { get; set; }
        public string Drug_Formula { get; set; }
        public string Molecular_Mass { get; set; }
        public string Compound_Structure_png { get; set; }
        public string Compound_CAS_ID { get; set; }
        public string PubChem_CID { get; set; }
        public string PubChem_Compound_Link { get; set; }
        public string ChEMBL_ID { get; set; }
        public string ChEMBL_Link { get; set; }
        public string CHEMBL_Kinase_SARFari_Link { get; set; }
        public string PubChem_SID { get; set; }
        public string PubChem_Substance_Link { get; set; }
        public string ChemSpider_ID { get; set; }
        public string ChemSpider_Link { get; set; }
        public string ChEBI_ID { get; set; }
        public string ChEBI_Link { get; set; }
        public string BindingDB_ID { get; set; }
        public string BindingDB_Link { get; set; }
        public string DrugBank_ID { get; set; }
        public string DrugBank_Link { get; set; }
        public string Drug_Registration_Number { get; set; }
        public string KEGG_Drug_ID { get; set; }
        public string KEGG_Drug_Link { get; set; }
        public string Therapeutic_Targets_ID { get; set; }
        public string Therapeutic_Targets_Link { get; set; }
        public string PharmGKB_ID { get; set; }
        public string PharmGKB_Link { get; set; }
        public string HET_ID { get; set; }
        public string HET_Link { get; set; }
        public string Drug_Product_ID { get; set; }
        public string Drug_Product_ID_Link { get; set; }
        public string RxList_ID { get; set; }
        public string RxList_Link { get; set; }
        public string Drugs_com_ID { get; set; }
        public string Drugs_com_Link { get; set; }
        public string Wikipedia { get; set; }
        public string Wikipedia_Link { get; set; }
        public string General_Targets { get; set; }
        public string General_Activity { get; set; }
        public string Commentary { get; set; }
        public string Source_Type { get; set; }
        public string Living_Source1 { get; set; }
        public string Living_Source2 { get; set; }
        public string Clinically_Approved { get; set; }
        public string Latest_Stage_Trials { get; set; }
        public string Producer { get; set; }
        public string Disease_Applications { get; set; }
        public string Toxic_Effects { get; set; }
        public string Reference_1 { get; set; }
        public string Reference_2 { get; set; }
        public string Commercial_Vendor { get; set; }
        public string Drug_PDB_ID_URL { get; set; }
        public string Column_58 { get; set; }
    }
}
