//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleDatabaseEntities : DbContext
    {
        public SampleDatabaseEntities()
            : base("name=SampleDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C18OC3_DrugProNET_A_Protein_Info> C18OC3_DrugProNET_A_Protein_Info { get; set; }
        public virtual DbSet<C18OC3_DrugProNET_B_Drug_Info> C18OC3_DrugProNET_B_Drug_Info { get; set; }
        public virtual DbSet<C18OC3_DrugProNET_C_PDB_Info> C18OC3_DrugProNET_C_PDB_Info { get; set; }
        public virtual DbSet<C18OC3_DrugProNET_D_Drug_Protein_AA_Interaction> C18OC3_DrugProNET_D_Drug_Protein_AA_Interaction { get; set; }
        public virtual DbSet<C18OC3_DrugProNET_E_Mutation_SNV> C18OC3_DrugProNET_E_Mutation_SNV { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
