//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDB_Information
    {
        public string PDB_File_ID { get; set; }
        public string Drug_PDB_ID { get; set; }
        public string UniProt_ID { get; set; }
        public string Drugs_and_Other_Ligands { get; set; }
        public string Method { get; set; }
        public string Resolution { get; set; }
        public string Residue_Count { get; set; }
        public string PDB_Released { get; set; }
        public string PDB_Entry_Title { get; set; }
        public string Authors { get; set; }
        public string Journal_Reference { get; set; }
        public string Ki_nM_ { get; set; }
        public string Kd_nM_ { get; set; }
        public string IC50_nM_ { get; set; }
        public string PDB_Protein_Name { get; set; }
        public string Protein_Short_Name { get; set; }
        public string DrugKiNET_Entered { get; set; }
    }
}
