//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDB_Interaction
    {
        public string UniProt_ID { get; set; }
        public string PDB_File_ID { get; set; }
        public string Drug_PDB_ID { get; set; }
        public string AA_Residue_Type { get; set; }
        public string UniProt_Residue_Number { get; set; }
        public string PDB_Residue_Number { get; set; }
        public string Number_of_Atomic_Interactions { get; set; }
        public string Average_Distance_Between_Atoms { get; set; }
        public string Interaction_Distance_Ratio { get; set; }
    }
}
