//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDB_Distances
    {
        public string PDB_Entry { get; set; }
        public double Distance { get; set; }
        public string Protein_Chain { get; set; }
        public string Protein_Atom { get; set; }
        public string Protein_Residue { get; set; }
        public int Protein_Residue_ { get; set; }
        public string Compound_Name { get; set; }
        public string Compound_Atom { get; set; }
    }
}
