//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDB_Distance
    {
        public string PDB_File_ID { get; set; }
        public string Protein_Chain { get; set; }
        public string Protein_Atom { get; set; }
        public string Protein_Residue { get; set; }
        public string Protein_Residue_Number { get; set; }
        public string Compound_Name { get; set; }
        public string Compound_Atom { get; set; }
        public string Distance { get; set; }
    }
}
