//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugProNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protein_Information
    {
        public string Uniprot_ID { get; set; }
        public string Protein_Short_Name { get; set; }
        public string Protein_Full_Name { get; set; }
        public string Protein_Alias { get; set; }
        public string Protein_Type_Specific { get; set; }
        public string Kinase_Group { get; set; }
        public string Kinase_Family { get; set; }
        public string Kinase_Subfamily { get; set; }
        public string GOCellComponent1 { get; set; }
        public string GOCellComponent1URL { get; set; }
        public string GOCellComponent2 { get; set; }
        public string GOCellComponent2URL { get; set; }
        public string GOCellComponent3 { get; set; }
        public string GOCellComponent3URL { get; set; }
        public string GOMolFunction1 { get; set; }
        public string GOMolFunction1URL { get; set; }
        public string GOMolFunction2 { get; set; }
        public string GOMolFunction2URL { get; set; }
        public string GOMolFunction3 { get; set; }
        public string GOMolFunction3URL { get; set; }
        public string GOBioProcess1 { get; set; }
        public string GOBioProcess1URL { get; set; }
        public string GOBioProcess2 { get; set; }
        public string GOBioProcess2URL { get; set; }
        public string GOBioProcess3 { get; set; }
        public string GOBioProcess3URL { get; set; }
        public string Protein_Mass { get; set; }
        public string Protein_AA_Number { get; set; }
        public string UniProt_Entry_URL { get; set; }
        public string Entry_ID { get; set; }
        public string NCBI_RefSeq_NP_ID { get; set; }
        public string NCBI_RefSeq_NP_ID_URL { get; set; }
        public string International_Prot_ID { get; set; }
        public string PhosphoNET_Name { get; set; }
        public string PhosphoNET_URL { get; set; }
        public string PhosphoSite_Plus_Entry { get; set; }
        public string PhosphoSite_Plus_Entry_URL { get; set; }
        public string KinaseNET_URL { get; set; }
        public string OncoNET_URL { get; set; }
        public string Kinex_Product_Links { get; set; }
        public string PDB_Protein_Name { get; set; }
        public string Human_Chromosome_Number { get; set; }
        public string Human_Chromosome_Location { get; set; }
        public string Human_Gene_Location { get; set; }
        public string NCBI_Nucleotide_ID { get; set; }
        public string NCBI_Nucleotide_ID_URL { get; set; }
        public string NCBI_Gene_ID { get; set; }
        public string NCBI_Gene_URL { get; set; }
        public string NCBI_Gene_Name { get; set; }
        public string NCBI_geneID { get; set; }
    }
}
